// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Lkcgm-69D9nWHx5wtQNXPUaqvmooThY',
    appId: '1:128067449633:web:8a2ec2b5ba7f41d60d4460',
    messagingSenderId: '128067449633',
    projectId: 'airpedia-11033',
    authDomain: 'airpedia-11033.firebaseapp.com',
    databaseURL: 'https://airpedia-11033-default-rtdb.firebaseio.com',
    storageBucket: 'airpedia-11033.appspot.com',
    measurementId: 'G-3TZHJ9G53J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtbIRKZsSyW8uwrRnxMQYZh6GGLxiKT5g',
    appId: '1:128067449633:android:15f36d43d12735870d4460',
    messagingSenderId: '128067449633',
    projectId: 'airpedia-11033',
    databaseURL: 'https://airpedia-11033-default-rtdb.firebaseio.com',
    storageBucket: 'airpedia-11033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8zTLYR64BQgnzPLqWqwH4BIMw8XIMmA0',
    appId: '1:128067449633:ios:17a693f80d9e1e480d4460',
    messagingSenderId: '128067449633',
    projectId: 'airpedia-11033',
    databaseURL: 'https://airpedia-11033-default-rtdb.firebaseio.com',
    storageBucket: 'airpedia-11033.appspot.com',
    androidClientId: '128067449633-8qe1cg21bfn21rdftjk2pu42v5bfggqi.apps.googleusercontent.com',
    iosClientId: '128067449633-kck1aj65qo70c8crprh7rdmt90h90dd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.airpedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8zTLYR64BQgnzPLqWqwH4BIMw8XIMmA0',
    appId: '1:128067449633:ios:fccf6d573346ea4b0d4460',
    messagingSenderId: '128067449633',
    projectId: 'airpedia-11033',
    databaseURL: 'https://airpedia-11033-default-rtdb.firebaseio.com',
    storageBucket: 'airpedia-11033.appspot.com',
    androidClientId: '128067449633-8qe1cg21bfn21rdftjk2pu42v5bfggqi.apps.googleusercontent.com',
    iosClientId: '128067449633-1q1f86d93coqkop4k52eo73k743lbge7.apps.googleusercontent.com',
    iosBundleId: 'com.example.airpedia.RunnerTests',
  );
}
